[workspace]
resolver = "2"
members = ["sbv2_api", "sbv2_core", "sbv2_bindings", "sbv2_web"]

[workspace.dependencies]
anyhow = "1.0.86"
dotenvy = "0.15.7"
env_logger = "0.11.5"
ndarray = "0.16.1"

[profile.release]
lto = true
debug = false
strip = true
